global:
  evaluation_interval: 15s
  scrape_interval: 5s

scrape_configs:
  - job_name: sso-metrics
    static_configs:
      - targets: [ "sso:9190" ]
  - job_name: sso-postgres-exporter
    static_configs:
      - targets: [ "postgres-exporter:9187" ]
  - job_name: sso-redis-exporter
    scrape_configs:
      - targets: [ "redis-exporter:9121" ]
