// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Access struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	DeviceID  pgtype.UUID
	Token     string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type App struct {
	ID     int64
	Name   string
	Secret string
	Scope  string
}

type Device struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	DeviceToken string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Login        string
	PasswordHash string
	FirstName    string
	LastName     string
	MiddleName   string
	Avatar       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type Verification struct {
	Email     string
	Type      string
	Code      string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}
